add_newline = true

format = """$os$directory$character"""
right_format = """$git_branch$git_status$time$cmd_duration"""

[os.symbols]
Arch = "󰣇"

[os]
disabled = false
format = '[ $symbol ](bg:yellow fg:black)[](fg:yellow)'

[character]
success_symbol = ""
error_symbol = "[](bold fg:red)[ ERRO ](bg:red fg:white)[ ](bold fg:red)"

[package]
disabled = false

[git_branch]
style = "bg: cyan"
symbol = "󰘬"
truncation_length = 12
truncation_symbol = ""
format = "[](bold fg:cyan)[ $symbol $branch(:$remote_branch)](fg:black bg:cyan)"

[git_metrics]
disabled = false
only_nonzero_diffs = true
added_style = 'bold blue'
format = '[(  $added )(  $deleted )](bg:cyan fg:black)[](fg:cyan)'

[git_status]
conflicted = "  ($count) "
ahead = "  ($count) "
behind = "   ($count) "
diverged = "   ($count) "
untracked = "  ($count) "
stashed = "  ($count) "
modified = "  ($count) "
staged = '  ($count) '
renamed = "  ($count) "
deleted = "  ($count) "
style = "bg: cyan"
format = '[ ($all_status)](bg:cyan fg:black)[](fg:cyan)'

[hostname]
ssh_only = false
format =  "[•$hostname](bg:cyan bold fg:black)[](bold fg:cyan)"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[username]
style_user = "bold bg:cyan fg:black"
style_root = "red bold"
format = "[](bold fg:cyan)[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = "~"
read_only = " "
style = "bg:green fg:black"
truncation_length = 3
truncation_symbol = "../"
format = '[](fg:green)[ 󰉋 $path ]($style)[](fg:green)'

[directory.substitutions]
"Documents" = "󰈔"
"Downloads" = ""

[time]
disabled = false
time_format = "%R"
format = '[](bold fg:yellow)[ $time ](bg:yellow fg:black)'

[cmd_duration]
format = '[ 󰔛 $duration ](bg:yellow fg:black)'
